CZBK.ItcastOA.WebApp/Controllers/RoleInfoController.cs
using CZBK.ItcastOA.Model;
using CZBK.ItcastOA.Model.EnumType;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZBK.ItcastOA.WebApp.Controllers
{
    public class RoleInfoController : BaseController
    {
        IBLL.IRoleinfoService RoleInfoService { get; set; }
        // GET: RoleInfo
        public ActionResult Index()
        {
            return View();
        }

        #region 获取角色列表
        public ActionResult GetRoleInfoList()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 5;
            int totalCount;
            short delFlag = (short)DeleteEnumType.Normarl;
            var roleInfoList = RoleInfoService.LoadPageEntities(pageIndex, pageSize, out totalCount,
                c => c.DELFLAG == delFlag, c => c.ID, true);
            var temp = from r in roleInfoList
                       select new
                       {
                           ID = r.ID,
                           ROLENAME = r.ROLENAME,
                           SORT = r.SORT,
                           REMARK = r.REMARK,
                           SUBTIME = r.SUBTIME
                       };
            return Json(new { rows = temp, total = totalCount, }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 展示添加表单
        public ActionResult ShowAddInfo()
        {
            return View();
        }
        #endregion


        #region 完成角色信息添加
        public ActionResult AddRoleInfo(ROLEINFO roleInfo)
        {
            roleInfo.MODIFIEDON = DateTime.Now;
            roleInfo.SUBTIME = DateTime.Now;
            roleInfo.DELFLAG = 0;
            RoleInfoService.AddEntity(roleInfo);
            return Content("ok");
        }
        #endregion
    }
}

CZBK.ItcastOA.WebApp/Views/RoleInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>角色管理</title>
    @*<link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
        <link href="~/Content/themes/icon.css" rel="stylesheet" />
        <script src="~/Scripts/jquery-1.7.1.min.js"></script>
        <script src="~/Scripts/jquery.easyui.min.js"></script>
        <script src="~/Scripts/easyui-lang-zh_CN.js"></script>*@
    <link href="~/Content/jquery-easyui-1.6.8/themes/icon.css" rel="stylesheet" />
    <link href="~/Content/jquery-easyui-1.6.8/themes/default/easyui.css" rel="stylesheet" />
    <script src="~/Content/jquery-easyui-1.6.8/jquery.min.js"></script>
    <script src="~/Content/jquery-easyui-1.6.8/jquery.easyui.min.js"></script>
    <script src="~/Content/jquery-easyui-1.6.8/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#addDiv").css("display", "none");
            $("#setActionDiv").css("display", "none");
            loadData();
        });

        function loadData(pars) {
            $('#tt').datagrid({
                url: '/RoleInfo/GetRoleInfoList',
                title: '角色数据表格',
                width: 700,
                height: 400,
                fitColumns: true, //列自适应
                nowrap: false,
                idField: 'ID',//主键列的列明
                loadMsg: '正在加载角色的信息...',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页多少条数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15],
                queryParams: pars,//往后台传递参数
                columns: [[//c.UserName, c.UserPass, c.Email, c.RegTime
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '编号', width: 80 },
                    { field: 'ROLENAME', title: '角色名称', width: 120 },
                    { field: 'SORT', title: '排序', width: 120 },
                    { field: 'REMARK', title: '备注', width: 120 },
                    {
                        field: 'SUBTIME', title: '时间', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d");
                        }
                    }
                ]],
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {

                        deleteInfo();
                    }
                }, {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {

                        addInfo();
                    }
                }, {
                    id: 'btnEdit',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {

                        showEditInfo();
                    }
                }],
            });
        }

        //添加信息
        function addInfo() {
            //给iframe指定页面的URL地址
            $("#addFrame").attr("src", "/RoleInfo/ShowAddInfo");
            $("#addDiv").css("display", "block");
            $('#addDiv').dialog({
                title: '添加角色数据',
                width: 300,
                height: 300,
                collapsible: true,
                maximizable: true,
                resizable: true,
                modal: true,
                buttons: [{
                    text: 'Ok',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        //调用子窗口的方法.
                        var childWindow = $("#addFrame")[0].contentWindow;//表示获取了嵌入在iframe中的子窗体的window对象。
                        childWindow.subForm();//调用子窗体中的方法，完成表单的提交。
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $('#addDiv').dialog('close');
                    }
                }]
            });
        }
        //添加完成后调用该方法。
        function afterAdd(data) {
            if (data == "ok") {
                $('#addDiv').dialog('close');
                $('#tt').datagrid('reload');//加载表格不会跳到第一页。
            }
        }
    </script>
</head>
<body>
    <div>
        <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit"></table>
    </div>
    <!------------添加表单------------------>
    <div id="addDiv">
        <iframe id="addFrame" width="100%" height="100%" frameborder="0"></iframe>
    </div>


    <!------------添加表单------------------>
    <div id="setActionDiv">
        <iframe id="setActionFrame" width="100%" height="100%" frameborder="0"></iframe>
    </div>
</body>
</html>

CZBK.ItcastOA.WebApp/Views/RoleInfo/ShowAddInfo.cshtml
@model CZBK.ItcastOA.Model.ROLEINFO

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>添加角色</title>
    @*<script src="~/Scripts/jquery-1.7.1.min.js"></script>*@
    <script src="~/Content/jquery-easyui-1.6.8/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function subForm() {
            $("#addRoleForm").submit();
        }
        function afterAdd(data) {
            //子窗体调用父窗体中的方法。
            window.parent.afterAdd(data);
        }
    </script>
</head>
<body>
    @using (Ajax.BeginForm("AddRoleInfo","RoleInfo", new { }, new AjaxOptions() { OnSuccess="afterAdd"},
        new { id = "addRoleForm" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ROLENAME, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ROLENAME, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ROLENAME, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.REMARK, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.REMARK, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.REMARK, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SORT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SORT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SORT, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    }
</body>
</html>